name: alt # active learning tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter
  - numpy
  - matplotlib
  - jupytext
  - ipi
  - pytorch>= 1.12
  - pip
  - pip:
      - mace-torch
