[project]
name = "alt"
description = "Active Learning Tutorial"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "jupyter",
    "ipywidgets",
    "numpy",
    "matplotlib",
    "ipi",
    "mace-torch",
    "multiprocessing", # optional
    "rich", # optional
    "ase",
    "tqdm",
    "scipy"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
